// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Infra.Data;

#nullable disable

namespace WebSales.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625205045_restartingMapping")]
    partial class restartingMapping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsLegalPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(2683),
                            Document = "195.980.823-00",
                            FullName = "Isabella Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(4262),
                            Document = "663.898.680-57",
                            FullName = "Melissa Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(5029),
                            Document = "518.108.324-20",
                            FullName = "Isaac Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(5661),
                            Document = "892.051.392-97",
                            FullName = "Nicolas Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(6309),
                            Document = "995.796.645-60",
                            FullName = "Salvador Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(6991),
                            Document = "226.907.589-70",
                            FullName = "Pietro Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(7600),
                            Document = "147.155.695-66",
                            FullName = "Ana Júlia Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(8210),
                            Document = "626.372.126-08",
                            FullName = "Guilherme Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(8834),
                            Document = "250.489.414-70",
                            FullName = "Yuri Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 26, DateTimeKind.Local).AddTicks(9460),
                            Document = "114.281.319-30",
                            FullName = "Lavínia Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(32),
                            Document = "180.862.167-05",
                            FullName = "Feliciano Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(667),
                            Document = "462.716.462-98",
                            FullName = "Joana Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(1246),
                            Document = "312.436.576-34",
                            FullName = "Vicente Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(1823),
                            Document = "747.204.589-63",
                            FullName = "Davi Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(2435),
                            Document = "433.866.610-25",
                            FullName = "Cecília Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(2998),
                            Document = "484.943.245-00",
                            FullName = "Lorraine Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(3587),
                            Document = "727.024.303-41",
                            FullName = "Giovanna Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(4137),
                            Document = "546.103.666-06",
                            FullName = "Júlia Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(4718),
                            Document = "143.664.451-82",
                            FullName = "Sara Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(5319),
                            Document = "214.499.810-89",
                            FullName = "Feliciano Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(5883),
                            Document = "042.494.910-56",
                            FullName = "Beatriz Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(6508),
                            Document = "320.483.829-32",
                            FullName = "Suélen Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(7108),
                            Document = "071.244.610-90",
                            FullName = "Samuel Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(7879),
                            Document = "637.593.597-01",
                            FullName = "Mércia Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(8475),
                            Document = "078.246.778-42",
                            FullName = "Gabriel Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(9074),
                            Document = "635.381.705-33",
                            FullName = "Lorraine Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 27, DateTimeKind.Local).AddTicks(9709),
                            Document = "969.275.364-69",
                            FullName = "Vitor Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(281),
                            Document = "727.591.674-61",
                            FullName = "Ana Júlia Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(910),
                            Document = "942.618.748-06",
                            FullName = "Samuel Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(1493),
                            Document = "884.335.643-74",
                            FullName = "Pablo Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(2146),
                            Document = "265.796.482-60",
                            FullName = "Ladislau Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(2772),
                            Document = "188.697.912-03",
                            FullName = "Meire Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(3375),
                            Document = "099.883.587-09",
                            FullName = "Gustavo Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(4016),
                            Document = "416.630.516-66",
                            FullName = "Lavínia Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(4609),
                            Document = "527.699.664-48",
                            FullName = "Núbia Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(5186),
                            Document = "890.955.628-59",
                            FullName = "César Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(5784),
                            Document = "530.249.930-45",
                            FullName = "Luiza Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(6358),
                            Document = "470.824.331-66",
                            FullName = "Frederico Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(6980),
                            Document = "564.486.988-17",
                            FullName = "Félix Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(7572),
                            Document = "934.137.372-79",
                            FullName = "Calebe Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(8171),
                            Document = "554.638.751-38",
                            FullName = "Margarida Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(8770),
                            Document = "172.936.144-70",
                            FullName = "Samuel Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(9372),
                            Document = "663.357.002-39",
                            FullName = "Marcos Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 28, DateTimeKind.Local).AddTicks(9942),
                            Document = "589.886.968-91",
                            FullName = "Anthony Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(602),
                            Document = "074.695.580-47",
                            FullName = "Maria Helena Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(1186),
                            Document = "843.051.453-83",
                            FullName = "Ana Clara Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(1811),
                            Document = "248.935.115-05",
                            FullName = "Washington Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(2392),
                            Document = "791.408.890-09",
                            FullName = "Maitê Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(3008),
                            Document = "161.750.730-02",
                            FullName = "Célia Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 29, DateTimeKind.Local).AddTicks(3607),
                            Document = "809.293.330-80",
                            FullName = "Víctor Oliveira",
                            IsLegalPerson = false
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7317),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Lindo Algodão Calças",
                            Price = 21.75840530093539m,
                            Quantity = 97
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7702),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Impressionante Congelado Camiseta",
                            Price = 94.185503736447529m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7745),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Lindo Aço Salada",
                            Price = 80.251066126857196m,
                            Quantity = 39
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7772),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Rústico Madeira Teclado",
                            Price = 11.469488728779982m,
                            Quantity = 31
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7795),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Feito à mão Plástico Salada",
                            Price = 19.064063576993896m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7816),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Incrível Plástico Mouse",
                            Price = 39.066545651160763m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7865),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Prático Macio Teclado",
                            Price = 93.31674988938688m,
                            Quantity = 29
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7893),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Genérico Aço Bacon",
                            Price = 61.748992511564995m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7912),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licenciado Plástico Sapatos",
                            Price = 84.534507562766293m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7932),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Feito à mão Algodão Chapéu",
                            Price = 17.490237370437754m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7950),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licenciado Borracha Bacon",
                            Price = 32.697640209982681m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7968),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licenciado Concreto Teclado",
                            Price = 27.954054335247193m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(7988),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Genérico Madeira Cadeira",
                            Price = 32.428889272749331m,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8007),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sem marca Concreto Mesa",
                            Price = 9.9929374198946425m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8025),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Lustroso Algodão Bicicleta",
                            Price = 72.846459740464552m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8047),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Lustroso Granito Camiseta",
                            Price = 61.610668572447928m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8093),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Refinado Congelado Teclado",
                            Price = 37.860232985228026m,
                            Quantity = 91
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8111),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Inteligente Granito Salada",
                            Price = 8.4723497775776773m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8129),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Prático Plástico Chapéu",
                            Price = 89.147253015174232m,
                            Quantity = 86
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8145),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Lustroso Aço Bola",
                            Price = 51.216486191057989m,
                            Quantity = 81
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8163),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incrível Macio Cadeira",
                            Price = 27.48777699474676m,
                            Quantity = 39
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8179),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Feito à mão Congelado Pizza",
                            Price = 49.25546908275016m,
                            Quantity = 66
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8196),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Inteligente Madeira Mesa",
                            Price = 17.27500660774219m,
                            Quantity = 99
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8214),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Genérico Congelado Toalhas",
                            Price = 76.154447332316143m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8231),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licenciado Concreto Bicicleta",
                            Price = 81.376484572060534m,
                            Quantity = 73
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8274),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rústico Aço Frango",
                            Price = 7.579274195976724m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8293),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Inteligente Granito Toalhas",
                            Price = 5.3227022818459645m,
                            Quantity = 91
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8309),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Feito à mão Borracha Salsicha",
                            Price = 62.492468302582372m,
                            Quantity = 31
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8326),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonômico Aço Toalhas",
                            Price = 82.843568247696112m,
                            Quantity = 59
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8344),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Pequeno Aço Salsicha",
                            Price = 57.17181991279177m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8362),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Prático Granito Bola",
                            Price = 51.833355990303403m,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8377),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Prático Madeira Teclado",
                            Price = 74.123653176811567m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8394),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Inteligente Metal Toalhas",
                            Price = 67.017722981849848m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8410),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Gostoso Fresco Atum",
                            Price = 77.651604097891273m,
                            Quantity = 83
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8469),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Refinado Congelado Bicicleta",
                            Price = 96.78867842394136m,
                            Quantity = 94
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8487),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Rústico Concreto Sabonete",
                            Price = 6.0013691119128583m,
                            Quantity = 99
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8503),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gostoso Macio Peixe",
                            Price = 47.803818569993155m,
                            Quantity = 58
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8520),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Pequeno Borracha Teclado",
                            Price = 29.635183544800096m,
                            Quantity = 43
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8535),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Refinado Concreto Frango",
                            Price = 58.126171351433734m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8550),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Licenciado Concreto Mesa",
                            Price = 21.477037422058822m,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8566),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Inteligente Borracha Salgadinhos",
                            Price = 3.9351347367425776m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8582),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Genérico Congelado Luvas",
                            Price = 52.367580663533101m,
                            Quantity = 86
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8598),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Inteligente Algodão Teclado",
                            Price = 79.73982273134098m,
                            Quantity = 58
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8640),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Refinado Aço Teclado",
                            Price = 78.739446460436398m,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8657),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Rústico Madeira Pizza",
                            Price = 92.969006323203064m,
                            Quantity = 19
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8674),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Lindo Borracha Bicicleta",
                            Price = 49.555903273666921m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8690),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Refinado Macio Toalhas",
                            Price = 12.781315867227148m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8706),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Pequeno Madeira Peixe",
                            Price = 3.249999627543613m,
                            Quantity = 58
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8722),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Licenciado Macio Salada",
                            Price = 96.765405000368851m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 31, DateTimeKind.Local).AddTicks(8737),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lindo Aço Bacon",
                            Price = 96.987091398668569m,
                            Quantity = 49
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPriceAtMoment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("SaleCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(8630),
                            CustomerId = 17,
                            ProductId = 14,
                            ProductPriceAtMoment = 10.690463541285763m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 149.666489578000682m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9043),
                            CustomerId = 9,
                            ProductId = 6,
                            ProductPriceAtMoment = 19.894162884436122m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 318.306606150977952m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9072),
                            CustomerId = 13,
                            ProductId = 8,
                            ProductPriceAtMoment = 15.800478972438193m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 316.009579448763860m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9091),
                            CustomerId = 15,
                            ProductId = 19,
                            ProductPriceAtMoment = 7.657404194726377m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 84.231446141990147m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9107),
                            CustomerId = 11,
                            ProductId = 6,
                            ProductPriceAtMoment = 11.549125107465522m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 150.138626397051786m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9122),
                            CustomerId = 3,
                            ProductId = 11,
                            ProductPriceAtMoment = 2.1868220774745808m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 19.6813986972712272m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9138),
                            CustomerId = 8,
                            ProductId = 13,
                            ProductPriceAtMoment = 5.207494140087989m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 104.149882801759780m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9151),
                            CustomerId = 10,
                            ProductId = 14,
                            ProductPriceAtMoment = 4.790034625853948m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 81.430588639517116m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9165),
                            CustomerId = 20,
                            ProductId = 7,
                            ProductPriceAtMoment = 13.99091360624317m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 237.84553130613389m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9205),
                            CustomerId = 12,
                            ProductId = 18,
                            ProductPriceAtMoment = 13.47399859582507m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 269.47997191650140m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9219),
                            CustomerId = 5,
                            ProductId = 11,
                            ProductPriceAtMoment = 4.164917426250761m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 20.824587131253805m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9232),
                            CustomerId = 7,
                            ProductId = 1,
                            ProductPriceAtMoment = 18.800532885328182m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 300.808526165250912m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9246),
                            CustomerId = 18,
                            ProductId = 11,
                            ProductPriceAtMoment = 3.499324113169555m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 34.993241131695550m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9258),
                            CustomerId = 12,
                            ProductId = 10,
                            ProductPriceAtMoment = 14.954150593526996m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 209.358108309377944m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9273),
                            CustomerId = 12,
                            ProductId = 3,
                            ProductPriceAtMoment = 5.432754145132751m,
                            ProductQuantity = 8,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 43.462033161062008m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9286),
                            CustomerId = 14,
                            ProductId = 20,
                            ProductPriceAtMoment = 14.588025843941795m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 131.292232595476155m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9299),
                            CustomerId = 6,
                            ProductId = 17,
                            ProductPriceAtMoment = 14.060668130742792m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 56.242672522971168m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9312),
                            CustomerId = 13,
                            ProductId = 15,
                            ProductPriceAtMoment = 6.75073547193635m,
                            ProductQuantity = 8,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 54.00588377549080m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9325),
                            CustomerId = 2,
                            ProductId = 3,
                            ProductPriceAtMoment = 18.484123761028869m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 18.484123761028869m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9380),
                            CustomerId = 4,
                            ProductId = 13,
                            ProductPriceAtMoment = 11.293067844244924m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 169.396017663673860m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9394),
                            CustomerId = 4,
                            ProductId = 18,
                            ProductPriceAtMoment = 2.3755305451167928m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 16.6287138158175496m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9407),
                            CustomerId = 12,
                            ProductId = 18,
                            ProductPriceAtMoment = 6.860929827584405m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 109.774877241350480m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9421),
                            CustomerId = 4,
                            ProductId = 1,
                            ProductPriceAtMoment = 6.85771001217027m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 130.29649023123513m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9434),
                            CustomerId = 2,
                            ProductId = 12,
                            ProductPriceAtMoment = 6.590959003024629m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 13.181918006049258m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9447),
                            CustomerId = 17,
                            ProductId = 12,
                            ProductPriceAtMoment = 15.43786269671536m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 46.31358809014608m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9460),
                            CustomerId = 15,
                            ProductId = 3,
                            ProductPriceAtMoment = 15.464437436424303m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 247.430998982788848m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9473),
                            CustomerId = 13,
                            ProductId = 18,
                            ProductPriceAtMoment = 8.988778623457678m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 161.798015222238204m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9486),
                            CustomerId = 19,
                            ProductId = 9,
                            ProductPriceAtMoment = 3.429356845628798m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 61.728423221318364m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9500),
                            CustomerId = 19,
                            ProductId = 4,
                            ProductPriceAtMoment = 6.543338329858119m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 19.630014989574357m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9513),
                            CustomerId = 6,
                            ProductId = 8,
                            ProductPriceAtMoment = 9.092226535734291m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 90.922265357342910m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9553),
                            CustomerId = 17,
                            ProductId = 4,
                            ProductPriceAtMoment = 4.599037682778072m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 68.985565241671080m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9568),
                            CustomerId = 9,
                            ProductId = 2,
                            ProductPriceAtMoment = 2.3031000496035168m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 27.6372005952422016m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9581),
                            CustomerId = 20,
                            ProductId = 5,
                            ProductPriceAtMoment = 4.354455696026397m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 47.899012656290367m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9594),
                            CustomerId = 6,
                            ProductId = 15,
                            ProductPriceAtMoment = 9.603871343994436m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 124.850327471927668m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9607),
                            CustomerId = 8,
                            ProductId = 14,
                            ProductPriceAtMoment = 4.790877282822217m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 86.235791090799906m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9620),
                            CustomerId = 2,
                            ProductId = 16,
                            ProductPriceAtMoment = 6.784399729836513m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 27.137598919346052m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9633),
                            CustomerId = 8,
                            ProductId = 5,
                            ProductPriceAtMoment = 15.030687308908502m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 75.153436544542510m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9647),
                            CustomerId = 3,
                            ProductId = 8,
                            ProductPriceAtMoment = 16.660646444469822m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 83.303232222349110m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9660),
                            CustomerId = 10,
                            ProductId = 18,
                            ProductPriceAtMoment = 12.409200070008031m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 198.547201120128496m
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9673),
                            CustomerId = 11,
                            ProductId = 19,
                            ProductPriceAtMoment = 4.167843948465419m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 66.685503175446704m
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9711),
                            CustomerId = 3,
                            ProductId = 16,
                            ProductPriceAtMoment = 6.906495532100589m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 34.532477660502945m
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9725),
                            CustomerId = 10,
                            ProductId = 20,
                            ProductPriceAtMoment = 13.277443646640038m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 39.832330939920114m
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9738),
                            CustomerId = 20,
                            ProductId = 7,
                            ProductPriceAtMoment = 10.890243036624364m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 43.560972146497456m
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9751),
                            CustomerId = 1,
                            ProductId = 3,
                            ProductPriceAtMoment = 9.735441477470533m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 68.148090342293731m
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9764),
                            CustomerId = 20,
                            ProductId = 12,
                            ProductPriceAtMoment = 17.241114629196428m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 189.652260921160708m
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9777),
                            CustomerId = 17,
                            ProductId = 4,
                            ProductPriceAtMoment = 3.935522005266081m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 55.097308073725134m
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9789),
                            CustomerId = 4,
                            ProductId = 18,
                            ProductPriceAtMoment = 1.8463664126811453m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 31.3882290155794701m
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9802),
                            CustomerId = 2,
                            ProductId = 4,
                            ProductPriceAtMoment = 16.536220158985422m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 165.362201589854220m
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9816),
                            CustomerId = 1,
                            ProductId = 19,
                            ProductPriceAtMoment = 13.979189651272466m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 139.791896512724660m
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 17, 50, 45, 33, DateTimeKind.Local).AddTicks(9829),
                            CustomerId = 19,
                            ProductId = 6,
                            ProductPriceAtMoment = 7.837026085098957m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230625175045",
                            Total = 101.881339106286441m
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebSales.Domain.Entities.Product", "Product")
                        .WithMany("ProductsSold")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSales");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsSold");
                });
#pragma warning restore 612, 618
        }
    }
}
