// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Infra.Data;

#nullable disable

namespace WebSales.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625184816_AddNewFieldsSale")]
    partial class AddNewFieldsSale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsLegalPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 473, DateTimeKind.Local).AddTicks(9869),
                            Document = "412.707.004-80",
                            FullName = "João Pedro Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(1379),
                            Document = "346.602.542-75",
                            FullName = "Raul Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(3404),
                            Document = "428.586.611-03",
                            FullName = "Clara Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(4799),
                            Document = "234.995.339-44",
                            FullName = "Lorena Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(5526),
                            Document = "067.397.269-06",
                            FullName = "Maria Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(6582),
                            Document = "607.461.384-23",
                            FullName = "Marli Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(8210),
                            Document = "679.661.881-59",
                            FullName = "Isis Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 474, DateTimeKind.Local).AddTicks(9367),
                            Document = "019.952.741-51",
                            FullName = "Isabelly Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(140),
                            Document = "570.618.354-60",
                            FullName = "Roberto Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(780),
                            Document = "267.238.126-70",
                            FullName = "Fabrício Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(2361),
                            Document = "448.083.202-58",
                            FullName = "Melissa Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(3347),
                            Document = "468.044.038-43",
                            FullName = "Sirineu Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(4907),
                            Document = "682.511.986-90",
                            FullName = "Isaac Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(5594),
                            Document = "405.007.309-97",
                            FullName = "Aline Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(6618),
                            Document = "208.343.405-69",
                            FullName = "Joaquim Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(7385),
                            Document = "567.685.896-60",
                            FullName = "Meire Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(8058),
                            Document = "694.903.488-13",
                            FullName = "Lucca Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(8685),
                            Document = "987.925.926-27",
                            FullName = "João Lucas Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(9294),
                            Document = "673.247.565-73",
                            FullName = "Alessandra Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 475, DateTimeKind.Local).AddTicks(9883),
                            Document = "891.623.849-88",
                            FullName = "Maria Eduarda Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(538),
                            Document = "772.386.990-87",
                            FullName = "Paulo Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(1158),
                            Document = "872.218.885-15",
                            FullName = "Rafaela Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(1805),
                            Document = "147.281.883-02",
                            FullName = "Sarah Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(2400),
                            Document = "401.219.706-12",
                            FullName = "Larissa Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(3076),
                            Document = "806.305.264-19",
                            FullName = "Liz Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(3687),
                            Document = "408.383.693-83",
                            FullName = "Enzo Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(4353),
                            Document = "331.930.055-50",
                            FullName = "Antônio Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(4959),
                            Document = "161.989.552-81",
                            FullName = "Felipe Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(5600),
                            Document = "474.852.033-71",
                            FullName = "Calebe Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(6325),
                            Document = "342.170.815-02",
                            FullName = "Tertuliano Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(6939),
                            Document = "611.185.493-33",
                            FullName = "Roberta Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(7621),
                            Document = "102.123.210-64",
                            FullName = "Lucas Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(8203),
                            Document = "600.375.012-08",
                            FullName = "Dalila Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 476, DateTimeKind.Local).AddTicks(8857),
                            Document = "174.744.142-28",
                            FullName = "Isadora Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(2260),
                            Document = "754.048.013-01",
                            FullName = "Rebeca Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(4662),
                            Document = "241.691.052-30",
                            FullName = "Gustavo Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(5389),
                            Document = "543.301.554-86",
                            FullName = "Noah Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(6371),
                            Document = "175.067.668-09",
                            FullName = "Gustavo Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(7377),
                            Document = "035.907.151-11",
                            FullName = "Lara Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(7986),
                            Document = "592.136.482-78",
                            FullName = "Aline Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(8685),
                            Document = "213.472.522-23",
                            FullName = "Gabriel Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(9323),
                            Document = "285.806.959-02",
                            FullName = "Laura Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 477, DateTimeKind.Local).AddTicks(9917),
                            Document = "832.939.597-92",
                            FullName = "Lorraine Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(1711),
                            Document = "141.936.850-80",
                            FullName = "Fabrícia Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(2466),
                            Document = "304.436.156-75",
                            FullName = "Lorena Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(3971),
                            Document = "727.060.292-18",
                            FullName = "Ana Júlia Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(4899),
                            Document = "758.458.310-59",
                            FullName = "Pablo Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(6454),
                            Document = "682.798.460-50",
                            FullName = "Kléber Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(7939),
                            Document = "630.729.309-88",
                            FullName = "Nataniel Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 478, DateTimeKind.Local).AddTicks(9083),
                            Document = "021.297.877-20",
                            FullName = "Clara Souza",
                            IsLegalPerson = false
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5282),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Inteligente Borracha Mouse",
                            Price = 79.4147592017373m,
                            Quantity = 96
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5738),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Rústico Metal Salsicha",
                            Price = 76.3739509378351m,
                            Quantity = 91
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5777),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Lindo Congelado Queijo",
                            Price = 15.0382468324067m,
                            Quantity = 49
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5804),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Inteligente Algodão Frango",
                            Price = 47.6566866538456m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5828),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Lindo Macio Frango",
                            Price = 14.3672494144282m,
                            Quantity = 75
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5849),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licenciado Borracha Computador",
                            Price = 41.1894103978207m,
                            Quantity = 70
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5871),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Incrível Fresco Queijo",
                            Price = 9.59979160314215m,
                            Quantity = 67
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5895),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Feito à mão Macio Salada",
                            Price = 85.7112374468327m,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5916),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Sem marca Concreto Mesa",
                            Price = 86.8467150423156m,
                            Quantity = 55
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(5983),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Feito à mão Congelado Mouse",
                            Price = 95.1734989063198m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6003),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Pequeno Concreto Pizza",
                            Price = 21.134732799732m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6022),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Prático Fresco Salada",
                            Price = 12.3528888646317m,
                            Quantity = 41
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6136),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Prático Borracha Bicicleta",
                            Price = 18.8487245376428m,
                            Quantity = 48
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6159),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Feito à mão Metal Camiseta",
                            Price = 56.4100095220469m,
                            Quantity = 89
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6176),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Genérico Metal Chapéu",
                            Price = 10.6045016774545m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6194),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Prático Macio Frango",
                            Price = 5.06205369966606m,
                            Quantity = 64
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6211),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Incrível Plástico Salada",
                            Price = 61.8985031767053m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6230),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Ergonômico Fresco Sapatos",
                            Price = 23.4282959659736m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6249),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Inteligente Algodão Cadeira",
                            Price = 89.9722241621967m,
                            Quantity = 36
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6316),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Ergonômico Concreto Salgadinhos",
                            Price = 1.02416213773123m,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6333),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Genérico Fresco Salgadinhos",
                            Price = 89.8243191649883m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6349),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Fantástico Concreto Computador",
                            Price = 58.8790413156479m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6367),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Licenciado Borracha Pizza",
                            Price = 46.2415469606129m,
                            Quantity = 91
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6385),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Prático Metal Peixe",
                            Price = 77.5895433533282m,
                            Quantity = 55
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6402),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rústico Fresco Computador",
                            Price = 27.9459552393588m,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6418),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Gostoso Madeira Calças",
                            Price = 97.008473093099m,
                            Quantity = 52
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6437),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Impressionante Aço Mesa",
                            Price = 51.8187184402849m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6455),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Sem marca Metal Mesa",
                            Price = 92.83490834016m,
                            Quantity = 96
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6527),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Refinado Fresco Atum",
                            Price = 71.9408853335263m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6547),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Pequeno Granito Salada",
                            Price = 5.81833872898542m,
                            Quantity = 82
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6565),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Feito à mão Concreto Luvas",
                            Price = 58.2614320472175m,
                            Quantity = 87
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6581),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Gostoso Granito Camiseta",
                            Price = 95.2631266249732m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6596),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Impressionante Macio Toalhas",
                            Price = 85.6621910084554m,
                            Quantity = 51
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6614),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Lindo Algodão Camiseta",
                            Price = 98.582756744269m,
                            Quantity = 54
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6630),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Pequeno Madeira Computador",
                            Price = 92.2812060890353m,
                            Quantity = 99
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6646),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Sem marca Macio Chapéu",
                            Price = 3.22457953318181m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6664),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Inteligente Concreto Computador",
                            Price = 80.1201187956506m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6681),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantástico Congelado Mesa",
                            Price = 77.572838402762m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6737),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Genérico Concreto Bicicleta",
                            Price = 95.0073322045197m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6754),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Ergonômico Borracha Cadeira",
                            Price = 74.5838380133999m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6771),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Refinado Madeira Bacon",
                            Price = 61.2851530802705m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6789),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Feito à mão Algodão Bicicleta",
                            Price = 41.6952310546839m,
                            Quantity = 87
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6805),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Lindo Aço Teclado",
                            Price = 17.3896294795714m,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6823),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Ergonômico Granito Bicicleta",
                            Price = 3.48271932889429m,
                            Quantity = 82
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6839),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Pequeno Metal Mouse",
                            Price = 37.3282447345513m,
                            Quantity = 57
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6856),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Genérico Borracha Salsicha",
                            Price = 43.6435122103621m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6872),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Lustroso Plástico Cadeira",
                            Price = 49.2681893863324m,
                            Quantity = 28
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6929),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sem marca Aço Bicicleta",
                            Price = 39.5405751340061m,
                            Quantity = 33
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6945),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Genérico Macio Calças",
                            Price = 46.3709752695432m,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 482, DateTimeKind.Local).AddTicks(6961),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Feito à mão Borracha Salgadinhos",
                            Price = 78.1053319104224m,
                            Quantity = 16
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("SoldDate");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPriceAtMoment")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("SaleCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(8651),
                            CustomerId = 5,
                            ProductId = 6,
                            ProductPriceAtMoment = 10.1519557516983m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 162.431292027173m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9116),
                            CustomerId = 5,
                            ProductId = 12,
                            ProductPriceAtMoment = 11.8206553787374m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 224.592452196011m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9140),
                            CustomerId = 16,
                            ProductId = 2,
                            ProductPriceAtMoment = 18.7956991056021m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 187.956991056021m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9156),
                            CustomerId = 13,
                            ProductId = 1,
                            ProductPriceAtMoment = 8.20305166950507m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 57.4213616865355m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9170),
                            CustomerId = 14,
                            ProductId = 12,
                            ProductPriceAtMoment = 4.78728937785889m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 43.08560440073m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9185),
                            CustomerId = 15,
                            ProductId = 14,
                            ProductPriceAtMoment = 17.6894060512799m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 70.7576242051195m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9200),
                            CustomerId = 7,
                            ProductId = 4,
                            ProductPriceAtMoment = 9.17046138870321m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 155.897843607955m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9213),
                            CustomerId = 9,
                            ProductId = 12,
                            ProductPriceAtMoment = 1.13026886077252m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 4.52107544309008m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9228),
                            CustomerId = 16,
                            ProductId = 18,
                            ProductPriceAtMoment = 9.7993953121794m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 19.5987906243588m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9280),
                            CustomerId = 12,
                            ProductId = 3,
                            ProductPriceAtMoment = 17.0680033839637m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 256.020050759456m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9296),
                            CustomerId = 11,
                            ProductId = 1,
                            ProductPriceAtMoment = 13.7960237004053m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 55.1840948016213m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9309),
                            CustomerId = 13,
                            ProductId = 19,
                            ProductPriceAtMoment = 5.22849204009061m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 26.142460200453m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9322),
                            CustomerId = 19,
                            ProductId = 16,
                            ProductPriceAtMoment = 18.2145694515059m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 218.574833418071m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9335),
                            CustomerId = 11,
                            ProductId = 1,
                            ProductPriceAtMoment = 3.91758920520049m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 74.4341948988094m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9348),
                            CustomerId = 1,
                            ProductId = 20,
                            ProductPriceAtMoment = 17.9346473345881m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 17.9346473345881m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9360),
                            CustomerId = 10,
                            ProductId = 17,
                            ProductPriceAtMoment = 3.07922174034129m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 27.7129956630716m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9373),
                            CustomerId = 7,
                            ProductId = 13,
                            ProductPriceAtMoment = 17.9661699833019m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 287.45871973283m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9386),
                            CustomerId = 7,
                            ProductId = 20,
                            ProductPriceAtMoment = 15.5258346274042m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 46.5775038822127m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9400),
                            CustomerId = 20,
                            ProductId = 9,
                            ProductPriceAtMoment = 2.01902005125739m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 36.342360922633m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9412),
                            CustomerId = 5,
                            ProductId = 3,
                            ProductPriceAtMoment = 15.427787078861m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 200.561232025192m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9464),
                            CustomerId = 11,
                            ProductId = 14,
                            ProductPriceAtMoment = 19.144445221944m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 38.288890443888m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9477),
                            CustomerId = 19,
                            ProductId = 17,
                            ProductPriceAtMoment = 10.8618339320012m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 32.5855017960036m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9491),
                            CustomerId = 17,
                            ProductId = 11,
                            ProductPriceAtMoment = 7.23011842632484m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 108.451776394873m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9503),
                            CustomerId = 3,
                            ProductId = 8,
                            ProductPriceAtMoment = 15.2117777829402m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 304.235555658804m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9517),
                            CustomerId = 13,
                            ProductId = 20,
                            ProductPriceAtMoment = 16.6893284950468m,
                            ProductQuantity = 8,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 133.514627960375m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9529),
                            CustomerId = 9,
                            ProductId = 11,
                            ProductPriceAtMoment = 1.03639685712369m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 9.32757171411325m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9541),
                            CustomerId = 8,
                            ProductId = 16,
                            ProductPriceAtMoment = 17.5541566176706m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 17.5541566176706m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9554),
                            CustomerId = 2,
                            ProductId = 14,
                            ProductPriceAtMoment = 17.079524704155m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 204.95429644986m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9566),
                            CustomerId = 18,
                            ProductId = 9,
                            ProductPriceAtMoment = 6.72362299216108m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 13.4472459843222m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9578),
                            CustomerId = 10,
                            ProductId = 7,
                            ProductPriceAtMoment = 7.5258037471325m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 75.258037471325m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9590),
                            CustomerId = 16,
                            ProductId = 4,
                            ProductPriceAtMoment = 16.5328099481915m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 181.860909430107m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9640),
                            CustomerId = 20,
                            ProductId = 11,
                            ProductPriceAtMoment = 11.3418657621997m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 158.786120670796m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9653),
                            CustomerId = 4,
                            ProductId = 17,
                            ProductPriceAtMoment = 11.9812126260284m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 71.8872757561702m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9666),
                            CustomerId = 8,
                            ProductId = 12,
                            ProductPriceAtMoment = 3.12525729009222m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 6.25051458018445m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9679),
                            CustomerId = 11,
                            ProductId = 7,
                            ProductPriceAtMoment = 19.0413030534594m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 247.536939694972m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9692),
                            CustomerId = 8,
                            ProductId = 11,
                            ProductPriceAtMoment = 19.9697179118506m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 239.636614942207m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9705),
                            CustomerId = 7,
                            ProductId = 4,
                            ProductPriceAtMoment = 8.83270345414276m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 158.98866217457m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9718),
                            CustomerId = 4,
                            ProductId = 10,
                            ProductPriceAtMoment = 3.11266233115662m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 31.1266233115662m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9730),
                            CustomerId = 5,
                            ProductId = 4,
                            ProductPriceAtMoment = 6.33207402049918m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 120.309406389484m
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9743),
                            CustomerId = 3,
                            ProductId = 12,
                            ProductPriceAtMoment = 1.16015970636217m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 10.4414373572595m
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9755),
                            CustomerId = 19,
                            ProductId = 4,
                            ProductPriceAtMoment = 7.83148127221561m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 156.629625444312m
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9768),
                            CustomerId = 19,
                            ProductId = 2,
                            ProductPriceAtMoment = 17.9723369935029m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 107.834021961018m
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9821),
                            CustomerId = 17,
                            ProductId = 12,
                            ProductPriceAtMoment = 1.25974872023846m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 11.3377384821461m
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9833),
                            CustomerId = 9,
                            ProductId = 8,
                            ProductPriceAtMoment = 8.18390415357829m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 114.574658150096m
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9845),
                            CustomerId = 3,
                            ProductId = 8,
                            ProductPriceAtMoment = 13.7207475455294m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 219.53196072847m
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9859),
                            CustomerId = 1,
                            ProductId = 15,
                            ProductPriceAtMoment = 9.81014535437577m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 117.721744252509m
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9872),
                            CustomerId = 2,
                            ProductId = 10,
                            ProductPriceAtMoment = 6.7907290376925m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 101.860935565387m
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9884),
                            CustomerId = 14,
                            ProductId = 2,
                            ProductPriceAtMoment = 8.72652273838013m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 165.803932029223m
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9896),
                            CustomerId = 13,
                            ProductId = 9,
                            ProductPriceAtMoment = 2.45340961985456m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 7.36022885956368m
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 15, 48, 16, 486, DateTimeKind.Local).AddTicks(9908),
                            CustomerId = 14,
                            ProductId = 2,
                            ProductPriceAtMoment = 18.973812081748m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230625154816",
                            Total = 189.73812081748m
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebSales.Domain.Entities.Product", "Product")
                        .WithMany("ProductsSold")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSales");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsSold");
                });
#pragma warning restore 612, 618
        }
    }
}
