// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Infra.Data;

#nullable disable

namespace WebSales.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625122136_addMocskData")]
    partial class addMocskData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsLegalPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(3391),
                            Document = "616.664.527-93",
                            FullName = "Paula Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(4836),
                            Document = "952.404.526-52",
                            FullName = "Lucca Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(5644),
                            Document = "759.943.442-90",
                            FullName = "Yago Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(6361),
                            Document = "576.635.825-35",
                            FullName = "Giovanna Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(7066),
                            Document = "906.515.194-03",
                            FullName = "Antonella Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(7760),
                            Document = "935.021.629-99",
                            FullName = "Melissa Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(8455),
                            Document = "584.826.358-24",
                            FullName = "Yasmin Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(9106),
                            Document = "565.670.080-16",
                            FullName = "Carlos Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 814, DateTimeKind.Local).AddTicks(9809),
                            Document = "151.473.824-45",
                            FullName = "Maria Luiza Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(450),
                            Document = "278.770.962-16",
                            FullName = "Arthur Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(1134),
                            Document = "846.477.364-15",
                            FullName = "Sophia Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(1833),
                            Document = "041.266.600-62",
                            FullName = "Salvador Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(2466),
                            Document = "474.529.844-71",
                            FullName = "Davi Lucca Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(3081),
                            Document = "813.396.741-49",
                            FullName = "Washington Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(3764),
                            Document = "180.101.465-52",
                            FullName = "Fábio Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(4462),
                            Document = "463.288.701-32",
                            FullName = "Carla Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(5158),
                            Document = "463.987.908-39",
                            FullName = "Heloísa Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(5813),
                            Document = "915.961.484-62",
                            FullName = "Karla Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(6484),
                            Document = "509.160.555-07",
                            FullName = "Suélen Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(7113),
                            Document = "859.581.703-09",
                            FullName = "Pietro Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(7814),
                            Document = "679.142.444-30",
                            FullName = "Beatriz Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(8478),
                            Document = "159.737.551-93",
                            FullName = "Leonardo Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(9109),
                            Document = "993.651.455-62",
                            FullName = "Félix Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 815, DateTimeKind.Local).AddTicks(9793),
                            Document = "365.996.772-66",
                            FullName = "Vicente Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(405),
                            Document = "111.738.855-79",
                            FullName = "Yasmin Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(1008),
                            Document = "294.235.662-60",
                            FullName = "Maria Clara Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(1680),
                            Document = "253.910.026-05",
                            FullName = "Bryan Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(2312),
                            Document = "803.730.112-53",
                            FullName = "Víctor Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(2961),
                            Document = "459.207.959-05",
                            FullName = "Isabelly Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(3583),
                            Document = "973.218.359-44",
                            FullName = "Carlos Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(4248),
                            Document = "406.702.882-25",
                            FullName = "Frederico Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(4862),
                            Document = "796.945.676-61",
                            FullName = "Hélio Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(5469),
                            Document = "308.640.360-86",
                            FullName = "Nicolas Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(6138),
                            Document = "608.691.842-29",
                            FullName = "Manuela Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(6835),
                            Document = "438.938.151-20",
                            FullName = "Mariana Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(7456),
                            Document = "514.745.427-60",
                            FullName = "Roberto Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(8085),
                            Document = "646.315.599-34",
                            FullName = "Guilherme Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(8740),
                            Document = "877.595.211-46",
                            FullName = "Felipe Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 816, DateTimeKind.Local).AddTicks(9379),
                            Document = "976.722.372-09",
                            FullName = "Víctor Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(36),
                            Document = "729.001.435-94",
                            FullName = "Hélio Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(633),
                            Document = "594.202.031-07",
                            FullName = "Laura Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(1304),
                            Document = "279.266.121-62",
                            FullName = "Aline Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(1900),
                            Document = "284.267.403-08",
                            FullName = "Sílvia Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(2563),
                            Document = "980.255.311-55",
                            FullName = "Melissa Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(3177),
                            Document = "128.491.869-61",
                            FullName = "Melissa Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(3834),
                            Document = "678.196.579-44",
                            FullName = "Bernardo Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(4482),
                            Document = "666.123.840-26",
                            FullName = "Marcos Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(5106),
                            Document = "872.000.494-09",
                            FullName = "Ígor Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(5757),
                            Document = "471.700.013-73",
                            FullName = "Vicente Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 817, DateTimeKind.Local).AddTicks(6442),
                            Document = "459.623.945-26",
                            FullName = "Felícia Melo",
                            IsLegalPerson = false
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2267),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantástico Plástico Queijo",
                            Price = 3.2260601133187m,
                            Quantity = 44
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2617),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Genérico Congelado Carro",
                            Price = 49.4264150699372m,
                            Quantity = 74
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2702),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Inteligente Algodão Bacon",
                            Price = 64.921245295969m,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2730),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Ergonômico Algodão Chapéu",
                            Price = 80.617138762519m,
                            Quantity = 64
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2752),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Sem marca Borracha Teclado",
                            Price = 83.6093871814624m,
                            Quantity = 39
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2773),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Lindo Concreto Carro",
                            Price = 94.6202007443819m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2794),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Genérico Metal Atum",
                            Price = 8.40349445237811m,
                            Quantity = 95
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2816),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Lustroso Borracha Queijo",
                            Price = 74.7672691419891m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2835),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Lindo Congelado Bola",
                            Price = 43.1596555563644m,
                            Quantity = 85
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2853),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Genérico Madeira Mouse",
                            Price = 4.76860813860034m,
                            Quantity = 69
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2872),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Pequeno Plástico Atum",
                            Price = 21.4444059783886m,
                            Quantity = 89
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2890),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Inteligente Congelado Sapatos",
                            Price = 77.1541537823514m,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2941),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Lustroso Metal Salsicha",
                            Price = 76.8072403636568m,
                            Quantity = 62
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2961),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Feito à mão Madeira Calças",
                            Price = 20.4543022547691m,
                            Quantity = 26
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(2980),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Lindo Plástico Pizza",
                            Price = 44.9044286417811m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3000),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rústico Aço Carro",
                            Price = 48.3866411034973m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3019),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Feito à mão Concreto Bicicleta",
                            Price = 79.9144063072098m,
                            Quantity = 44
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3038),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incrível Borracha Camiseta",
                            Price = 82.9785707243832m,
                            Quantity = 72
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3057),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Feito à mão Metal Chapéu",
                            Price = 50.7248554493696m,
                            Quantity = 77
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3076),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sem marca Borracha Computador",
                            Price = 89.6432317952364m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3093),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Incrível Macio Bicicleta",
                            Price = 8.59138467572118m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3139),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Fantástico Granito Mouse",
                            Price = 97.7001138375038m,
                            Quantity = 69
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3160),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Inteligente Borracha Peixe",
                            Price = 40.2639350485322m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3178),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Inteligente Concreto Queijo",
                            Price = 77.9556137121684m,
                            Quantity = 21
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3195),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Fantástico Borracha Carro",
                            Price = 3.12974928624601m,
                            Quantity = 93
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3212),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incrível Borracha Atum",
                            Price = 18.689293242402m,
                            Quantity = 74
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3228),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Licenciado Algodão Mesa",
                            Price = 20.1918166644832m,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3247),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Gostoso Madeira Cadeira",
                            Price = 78.4731147634696m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3265),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Incrível Macio Frango",
                            Price = 10.9938698560075m,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3283),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Lindo Fresco Sabonete",
                            Price = 64.9388819709027m,
                            Quantity = 33
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3301),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Prático Aço Salsicha",
                            Price = 64.0428334380816m,
                            Quantity = 46
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3350),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Sem marca Metal Peixe",
                            Price = 86.8052472719766m,
                            Quantity = 87
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3368),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Feito à mão Fresco Camiseta",
                            Price = 4.88213602381913m,
                            Quantity = 42
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3385),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Sem marca Aço Sabonete",
                            Price = 12.537422867696m,
                            Quantity = 92
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3402),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Lindo Aço Chapéu",
                            Price = 11.9133554709403m,
                            Quantity = 24
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3420),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lindo Concreto Frango",
                            Price = 87.8125042731304m,
                            Quantity = 41
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3438),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Ergonômico Borracha Toalhas",
                            Price = 2.91066183938879m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3454),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Rústico Plástico Carro",
                            Price = 64.9862249885696m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3471),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Lindo Algodão Sapatos",
                            Price = 20.4501436472683m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3488),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Prático Metal Computador",
                            Price = 85.2322955424581m,
                            Quantity = 66
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3535),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Prático Plástico Sabonete",
                            Price = 96.3378731861356m,
                            Quantity = 74
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3552),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Feito à mão Aço Pizza",
                            Price = 35.5288115482279m,
                            Quantity = 55
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3570),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Licenciado Macio Sabonete",
                            Price = 92.9092475932598m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3587),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Prático Metal Calças",
                            Price = 19.3936510759952m,
                            Quantity = 63
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3604),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Feito à mão Algodão Mouse",
                            Price = 51.8409776192202m,
                            Quantity = 54
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3623),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Licenciado Algodão Calças",
                            Price = 37.9418111571118m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3641),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Feito à mão Macio Luvas",
                            Price = 22.2751843918901m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3662),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Genérico Aço Salgadinhos",
                            Price = 27.4065009642632m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3681),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Genérico Algodão Salgadinhos",
                            Price = 22.9676047501907m,
                            Quantity = 54
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 819, DateTimeKind.Local).AddTicks(3728),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rústico Fresco Chapéu",
                            Price = 2.36348039464166m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(8680),
                            CustomerId = 2,
                            ProductId = 9,
                            Quantity = 4,
                            SaleNumber = "20230625092135",
                            Total = 12.0599728219512m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9044),
                            CustomerId = 15,
                            ProductId = 11,
                            Quantity = 16,
                            SaleNumber = "20230625092135",
                            Total = 11.0891555657476m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9070),
                            CustomerId = 18,
                            ProductId = 11,
                            Quantity = 4,
                            SaleNumber = "20230625092135",
                            Total = 19.39101614775m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9087),
                            CustomerId = 4,
                            ProductId = 14,
                            Quantity = 6,
                            SaleNumber = "20230625092135",
                            Total = 16.7870569116519m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9102),
                            CustomerId = 7,
                            ProductId = 19,
                            Quantity = 17,
                            SaleNumber = "20230625092135",
                            Total = 11.188731018016m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9115),
                            CustomerId = 11,
                            ProductId = 15,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 17.5857005960636m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9127),
                            CustomerId = 6,
                            ProductId = 14,
                            Quantity = 8,
                            SaleNumber = "20230625092135",
                            Total = 13.150091710505m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9138),
                            CustomerId = 6,
                            ProductId = 17,
                            Quantity = 20,
                            SaleNumber = "20230625092135",
                            Total = 16.5596374972735m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9180),
                            CustomerId = 9,
                            ProductId = 10,
                            Quantity = 15,
                            SaleNumber = "20230625092135",
                            Total = 14.7905979779994m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9194),
                            CustomerId = 4,
                            ProductId = 12,
                            Quantity = 7,
                            SaleNumber = "20230625092135",
                            Total = 5.57791800335351m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9206),
                            CustomerId = 6,
                            ProductId = 20,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 7.64113882112822m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9217),
                            CustomerId = 1,
                            ProductId = 5,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 5.65973378930819m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9229),
                            CustomerId = 4,
                            ProductId = 16,
                            Quantity = 20,
                            SaleNumber = "20230625092135",
                            Total = 1.61544871727962m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9241),
                            CustomerId = 8,
                            ProductId = 9,
                            Quantity = 2,
                            SaleNumber = "20230625092135",
                            Total = 19.4551426107951m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9252),
                            CustomerId = 14,
                            ProductId = 5,
                            Quantity = 20,
                            SaleNumber = "20230625092135",
                            Total = 10.4561311994032m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9264),
                            CustomerId = 1,
                            ProductId = 16,
                            Quantity = 20,
                            SaleNumber = "20230625092135",
                            Total = 17.9228148317356m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9276),
                            CustomerId = 11,
                            ProductId = 17,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 2.21701989344065m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9288),
                            CustomerId = 3,
                            ProductId = 5,
                            Quantity = 19,
                            SaleNumber = "20230625092135",
                            Total = 1.96963410403108m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9299),
                            CustomerId = 13,
                            ProductId = 3,
                            Quantity = 11,
                            SaleNumber = "20230625092135",
                            Total = 18.0260958883808m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9311),
                            CustomerId = 13,
                            ProductId = 8,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 18.8939333879769m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9362),
                            CustomerId = 20,
                            ProductId = 6,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 1.17508268132645m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9374),
                            CustomerId = 7,
                            ProductId = 6,
                            Quantity = 12,
                            SaleNumber = "20230625092135",
                            Total = 11.0630935313613m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9385),
                            CustomerId = 19,
                            ProductId = 16,
                            Quantity = 11,
                            SaleNumber = "20230625092135",
                            Total = 17.0940997408982m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9397),
                            CustomerId = 20,
                            ProductId = 2,
                            Quantity = 13,
                            SaleNumber = "20230625092135",
                            Total = 12.0075490237452m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9408),
                            CustomerId = 10,
                            ProductId = 11,
                            Quantity = 11,
                            SaleNumber = "20230625092135",
                            Total = 14.5857279930186m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9418),
                            CustomerId = 13,
                            ProductId = 20,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 9.73792210747728m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9430),
                            CustomerId = 10,
                            ProductId = 20,
                            Quantity = 18,
                            SaleNumber = "20230625092135",
                            Total = 10.1646144334258m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9441),
                            CustomerId = 9,
                            ProductId = 2,
                            Quantity = 20,
                            SaleNumber = "20230625092135",
                            Total = 14.8082440228494m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9453),
                            CustomerId = 7,
                            ProductId = 16,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 8.33095402018041m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9464),
                            CustomerId = 6,
                            ProductId = 1,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 2.30292359318265m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9476),
                            CustomerId = 17,
                            ProductId = 8,
                            Quantity = 19,
                            SaleNumber = "20230625092135",
                            Total = 6.87399837973104m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9519),
                            CustomerId = 3,
                            ProductId = 18,
                            Quantity = 3,
                            SaleNumber = "20230625092135",
                            Total = 15.5688262046541m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9534),
                            CustomerId = 18,
                            ProductId = 8,
                            Quantity = 4,
                            SaleNumber = "20230625092135",
                            Total = 1.33205840180562m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9546),
                            CustomerId = 1,
                            ProductId = 9,
                            Quantity = 18,
                            SaleNumber = "20230625092135",
                            Total = 4.39925372706208m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9558),
                            CustomerId = 7,
                            ProductId = 11,
                            Quantity = 12,
                            SaleNumber = "20230625092135",
                            Total = 2.77380499156315m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9570),
                            CustomerId = 4,
                            ProductId = 20,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 7.2038052955723m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9581),
                            CustomerId = 5,
                            ProductId = 8,
                            Quantity = 17,
                            SaleNumber = "20230625092135",
                            Total = 8.01934344228194m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9592),
                            CustomerId = 4,
                            ProductId = 5,
                            Quantity = 8,
                            SaleNumber = "20230625092135",
                            Total = 13.7571756784799m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9604),
                            CustomerId = 9,
                            ProductId = 1,
                            Quantity = 12,
                            SaleNumber = "20230625092135",
                            Total = 1.37385995959581m
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9616),
                            CustomerId = 2,
                            ProductId = 2,
                            Quantity = 15,
                            SaleNumber = "20230625092135",
                            Total = 3.8246084557438m
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9627),
                            CustomerId = 5,
                            ProductId = 6,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 8.14486467562757m
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9638),
                            CustomerId = 10,
                            ProductId = 5,
                            Quantity = 16,
                            SaleNumber = "20230625092135",
                            Total = 11.0487359988582m
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9648),
                            CustomerId = 6,
                            ProductId = 3,
                            Quantity = 1,
                            SaleNumber = "20230625092135",
                            Total = 7.60569617894687m
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9689),
                            CustomerId = 8,
                            ProductId = 2,
                            Quantity = 12,
                            SaleNumber = "20230625092135",
                            Total = 10.2426620488511m
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9701),
                            CustomerId = 13,
                            ProductId = 14,
                            Quantity = 14,
                            SaleNumber = "20230625092135",
                            Total = 11.2251596905829m
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9711),
                            CustomerId = 18,
                            ProductId = 6,
                            Quantity = 12,
                            SaleNumber = "20230625092135",
                            Total = 9.88786347600797m
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9722),
                            CustomerId = 19,
                            ProductId = 17,
                            Quantity = 11,
                            SaleNumber = "20230625092135",
                            Total = 12.5204049249346m
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9733),
                            CustomerId = 13,
                            ProductId = 20,
                            Quantity = 7,
                            SaleNumber = "20230625092135",
                            Total = 17.0247149843113m
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9744),
                            CustomerId = 2,
                            ProductId = 13,
                            Quantity = 8,
                            SaleNumber = "20230625092135",
                            Total = 3.7760203067003m
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 21, 35, 820, DateTimeKind.Local).AddTicks(9755),
                            CustomerId = 14,
                            ProductId = 6,
                            Quantity = 2,
                            SaleNumber = "20230625092135",
                            Total = 11.2529439470115m
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebSales.Domain.Entities.Product", "Product")
                        .WithMany("ProductsSold")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSales");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsSold");
                });
#pragma warning restore 612, 618
        }
    }
}
