// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Infra.Data;

#nullable disable

namespace WebSales.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625121216_addCustomerDataMock")]
    partial class addCustomerDataMock
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsLegalPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 748, DateTimeKind.Local).AddTicks(6256),
                            Document = "282.502.923-83",
                            FullName = "Bruna Moraes",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 748, DateTimeKind.Local).AddTicks(7734),
                            Document = "262.528.966-08",
                            FullName = "Tertuliano Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 748, DateTimeKind.Local).AddTicks(8484),
                            Document = "495.867.274-59",
                            FullName = "Maria Cecília Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 748, DateTimeKind.Local).AddTicks(9247),
                            Document = "589.847.480-30",
                            FullName = "Lara Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 748, DateTimeKind.Local).AddTicks(9982),
                            Document = "112.460.099-00",
                            FullName = "Lucca Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(662),
                            Document = "878.186.920-70",
                            FullName = "Esther Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(1360),
                            Document = "027.817.606-25",
                            FullName = "Lucca Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(1949),
                            Document = "983.633.042-98",
                            FullName = "Lavínia Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(2633),
                            Document = "459.977.356-56",
                            FullName = "Caio Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(3236),
                            Document = "899.166.005-38",
                            FullName = "Alice Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(3889),
                            Document = "947.922.857-20",
                            FullName = "Isabella Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(4519),
                            Document = "719.988.073-12",
                            FullName = "Vitória Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(5104),
                            Document = "536.160.620-04",
                            FullName = "Leonardo Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(5723),
                            Document = "179.240.155-82",
                            FullName = "João Miguel Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(6325),
                            Document = "750.220.650-70",
                            FullName = "Norberto Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(6946),
                            Document = "723.222.904-67",
                            FullName = "Giovanna Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(7511),
                            Document = "431.814.675-88",
                            FullName = "Lucca Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(8126),
                            Document = "172.106.031-66",
                            FullName = "Núbia Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(8735),
                            Document = "751.709.501-36",
                            FullName = "Elisa Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 749, DateTimeKind.Local).AddTicks(9414),
                            Document = "111.286.938-79",
                            FullName = "Maria Helena Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(3),
                            Document = "357.552.965-53",
                            FullName = "Clara Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(646),
                            Document = "127.584.013-20",
                            FullName = "Enzo Gabriel Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(1220),
                            Document = "951.540.371-54",
                            FullName = "Meire Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(1834),
                            Document = "811.276.888-98",
                            FullName = "Roberta Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(2467),
                            Document = "325.222.489-52",
                            FullName = "Silas Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(3030),
                            Document = "431.003.606-64",
                            FullName = "Ana Clara Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(3609),
                            Document = "510.551.272-32",
                            FullName = "Morgana Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(4246),
                            Document = "269.781.353-56",
                            FullName = "Luiza Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(4806),
                            Document = "957.685.976-03",
                            FullName = "Felícia Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(5442),
                            Document = "700.898.366-26",
                            FullName = "Bryan Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(6025),
                            Document = "275.859.617-23",
                            FullName = "Júlio César Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(6616),
                            Document = "492.978.028-42",
                            FullName = "Gabriel Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(7179),
                            Document = "937.219.318-66",
                            FullName = "Cecília Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(7743),
                            Document = "440.030.666-69",
                            FullName = "Natália Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(8400),
                            Document = "755.395.317-28",
                            FullName = "Suélen Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(8933),
                            Document = "057.652.408-52",
                            FullName = "Beatriz Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 750, DateTimeKind.Local).AddTicks(9767),
                            Document = "649.989.072-39",
                            FullName = "Lorenzo Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(458),
                            Document = "871.801.114-49",
                            FullName = "Valentina Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(1050),
                            Document = "140.279.309-08",
                            FullName = "Maria Helena Souza",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(1672),
                            Document = "207.011.131-89",
                            FullName = "Noah Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(2243),
                            Document = "466.716.060-80",
                            FullName = "Antônio Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(3003),
                            Document = "470.147.392-80",
                            FullName = "Pedro Henrique Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(3639),
                            Document = "538.407.366-76",
                            FullName = "Lucas Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(4342),
                            Document = "752.161.147-00",
                            FullName = "Heloísa Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(4960),
                            Document = "912.823.965-28",
                            FullName = "Valentina Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(5537),
                            Document = "758.099.876-99",
                            FullName = "Deneval Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(6188),
                            Document = "102.403.931-55",
                            FullName = "Isabella Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(6799),
                            Document = "595.296.485-02",
                            FullName = "Natália Pereira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(7404),
                            Document = "754.713.135-26",
                            FullName = "Helena Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 25, 9, 12, 16, 751, DateTimeKind.Local).AddTicks(8035),
                            Document = "747.732.426-20",
                            FullName = "João Lucas Moraes",
                            IsLegalPerson = false
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebSales.Domain.Entities.Product", "Product")
                        .WithMany("ProductsSold")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSales");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsSold");
                });
#pragma warning restore 612, 618
        }
    }
}
