// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSales.Infra.Data;

#nullable disable

namespace WebSales.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230628112632_reapplyingMigraitons")]
    partial class reapplyingMigraitons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsLegalPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(1756),
                            Document = "424.030.661-25",
                            FullName = "Cauã Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(3145),
                            Document = "982.928.763-75",
                            FullName = "Fabrício Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(3900),
                            Document = "628.810.506-62",
                            FullName = "Lorraine Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(4542),
                            Document = "649.804.469-14",
                            FullName = "Hugo Martins",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(5160),
                            Document = "388.272.557-53",
                            FullName = "Yasmin Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(5911),
                            Document = "597.065.680-18",
                            FullName = "Alessandra Franco",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(6548),
                            Document = "809.012.755-06",
                            FullName = "Ígor Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(7161),
                            Document = "564.095.429-92",
                            FullName = "Guilherme Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(7873),
                            Document = "072.324.358-19",
                            FullName = "Antonella Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(8482),
                            Document = "254.784.466-45",
                            FullName = "Cecília Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(9022),
                            Document = "017.089.845-85",
                            FullName = "Lucca Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 525, DateTimeKind.Local).AddTicks(9648),
                            Document = "078.252.877-54",
                            FullName = "Enzo Silva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(186),
                            Document = "346.433.737-50",
                            FullName = "Maria Luiza Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(731),
                            Document = "851.567.451-30",
                            FullName = "Marcos Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(1362),
                            Document = "167.475.746-80",
                            FullName = "Leonardo Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(1963),
                            Document = "256.053.740-01",
                            FullName = "César Nogueira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(2490),
                            Document = "215.327.505-95",
                            FullName = "Maria Eduarda Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(3108),
                            Document = "483.357.938-32",
                            FullName = "Mariana Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(3689),
                            Document = "409.190.461-00",
                            FullName = "Paula Oliveira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(4289),
                            Document = "676.714.990-05",
                            FullName = "Calebe Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(4835),
                            Document = "233.331.438-95",
                            FullName = "Eduardo Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(5426),
                            Document = "596.675.213-38",
                            FullName = "Márcia Xavier",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(6024),
                            Document = "911.522.768-59",
                            FullName = "Valentina Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(6617),
                            Document = "953.918.468-11",
                            FullName = "Félix Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(7157),
                            Document = "056.750.626-61",
                            FullName = "Dalila Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(7741),
                            Document = "999.200.108-98",
                            FullName = "Noah Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(8284),
                            Document = "166.655.046-97",
                            FullName = "Alexandre Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(8851),
                            Document = "943.625.710-43",
                            FullName = "Leonardo Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(9431),
                            Document = "404.856.622-99",
                            FullName = "Elísio Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 526, DateTimeKind.Local).AddTicks(9977),
                            Document = "220.605.613-53",
                            FullName = "Yago Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(589),
                            Document = "111.999.601-52",
                            FullName = "Matheus Santos",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(1128),
                            Document = "263.477.590-39",
                            FullName = "Antonella Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(1682),
                            Document = "979.776.586-58",
                            FullName = "Manuela Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(2228),
                            Document = "740.455.297-48",
                            FullName = "Benjamin Costa",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(2823),
                            Document = "511.587.408-32",
                            FullName = "Isaac Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(3375),
                            Document = "667.104.484-87",
                            FullName = "Bernardo Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(3931),
                            Document = "462.614.142-03",
                            FullName = "Yango Barros",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(4497),
                            Document = "794.189.137-98",
                            FullName = "Gael Macedo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(5047),
                            Document = "124.783.458-11",
                            FullName = "Yago Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(5596),
                            Document = "339.128.819-10",
                            FullName = "Silas Melo",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(6185),
                            Document = "644.687.381-62",
                            FullName = "João Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(6710),
                            Document = "091.768.631-40",
                            FullName = "Fabrício Carvalho",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(7283),
                            Document = "704.419.995-06",
                            FullName = "Warley Reis",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(7831),
                            Document = "579.618.783-00",
                            FullName = "Davi Moreira",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(8434),
                            Document = "492.668.640-64",
                            FullName = "Júlio César Albuquerque",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(8976),
                            Document = "854.127.857-35",
                            FullName = "Eduarda Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 527, DateTimeKind.Local).AddTicks(9571),
                            Document = "211.664.623-58",
                            FullName = "Raul Braga",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 528, DateTimeKind.Local).AddTicks(105),
                            Document = "611.992.281-41",
                            FullName = "Sirineu Batista",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 528, DateTimeKind.Local).AddTicks(627),
                            Document = "448.052.545-99",
                            FullName = "Liz Saraiva",
                            IsLegalPerson = false
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 528, DateTimeKind.Local).AddTicks(1197),
                            Document = "712.420.218-33",
                            FullName = "Ana Luiza Barros",
                            IsLegalPerson = false
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5128),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Prático Madeira Bicicleta",
                            Price = 56.625165376139854m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5459),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Genérico Concreto Bicicleta",
                            Price = 88.437053101475341m,
                            Quantity = 43
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5492),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Fantástico Concreto Sapatos",
                            Price = 93.125435412726298m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5519),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Genérico Congelado Frango",
                            Price = 94.875986048452003m,
                            Quantity = 92
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5548),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Licenciado Plástico Chapéu",
                            Price = 75.628417867063093m,
                            Quantity = 29
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5568),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Fantástico Aço Carro",
                            Price = 11.92574065245058m,
                            Quantity = 91
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5591),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Genérico Congelado Sabonete",
                            Price = 65.181324711842371m,
                            Quantity = 65
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5611),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licenciado Macio Pizza",
                            Price = 1.11478377494954458m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5659),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Inteligente Madeira Luvas",
                            Price = 52.212469633555186m,
                            Quantity = 87
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5679),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Licenciado Macio Calças",
                            Price = 57.209320283680432m,
                            Quantity = 67
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5697),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Sem marca Borracha Camiseta",
                            Price = 23.30702447240674m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5717),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Impressionante Plástico Camiseta",
                            Price = 62.361556477211485m,
                            Quantity = 97
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5735),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Genérico Granito Computador",
                            Price = 51.48897428624896m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5755),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Lustroso Madeira Cadeira",
                            Price = 23.43977665565482m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5774),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Refinado Congelado Frango",
                            Price = 51.131205546650173m,
                            Quantity = 65
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5793),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lindo Metal Peixe",
                            Price = 52.422762173321539m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5812),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Impressionante Algodão Luvas",
                            Price = 69.615769079063998m,
                            Quantity = 81
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5853),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Rústico Macio Chapéu",
                            Price = 81.46519731748234m,
                            Quantity = 88
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5872),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Licenciado Granito Chapéu",
                            Price = 32.69119689635185m,
                            Quantity = 17
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5890),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Pequeno Aço Sabonete",
                            Price = 39.324312213561649m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5908),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Refinado Metal Salada",
                            Price = 37.407141829838197m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5926),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Gostoso Congelado Camiseta",
                            Price = 27.41720885567038m,
                            Quantity = 34
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5947),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Inteligente Aço Peixe",
                            Price = 29.788331760341164m,
                            Quantity = 93
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5963),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Name = "Refinado Algodão Bola",
                            Price = 49.190836371165037m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5980),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Prático Borracha Mouse",
                            Price = 68.069001503595124m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(5997),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Pequeno Madeira Chapéu",
                            Price = 46.094158297615834m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6014),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Pequeno Congelado Sabonete",
                            Price = 48.438529601862916m,
                            Quantity = 56
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6071),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Incrível Metal Teclado",
                            Price = 95.184875937650212m,
                            Quantity = 54
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6088),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Feito à mão Congelado Salsicha",
                            Price = 89.377528785165631m,
                            Quantity = 18
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6106),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Prático Aço Peixe",
                            Price = 93.660737336789644m,
                            Quantity = 61
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6124),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Pequeno Granito Salgadinhos",
                            Price = 87.943321625122072m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6141),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Inteligente Metal Teclado",
                            Price = 66.534765376668841m,
                            Quantity = 96
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6158),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Incrível Concreto Salada",
                            Price = 75.70760084144335m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6176),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Inteligente Madeira Bola",
                            Price = 16.168488399330013m,
                            Quantity = 32
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6192),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Genérico Granito Atum",
                            Price = 50.437626124283353m,
                            Quantity = 42
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6209),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Feito à mão Fresco Queijo",
                            Price = 74.415714959333197m,
                            Quantity = 78
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6252),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Incrível Madeira Queijo",
                            Price = 26.375699030856328m,
                            Quantity = 67
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6270),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Ergonômico Macio Calças",
                            Price = 57.903818557025638m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6289),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Ergonômico Macio Calças",
                            Price = 20.721460048272928m,
                            Quantity = 31
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6306),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Licenciado Madeira Atum",
                            Price = 47.189998675381429m,
                            Quantity = 93
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6323),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Rústico Congelado Salada",
                            Price = 95.073605614451584m,
                            Quantity = 45
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6340),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Refinado Borracha Calças",
                            Price = 94.37015862387235m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6357),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Fantástico Congelado Calças",
                            Price = 46.412714686910032m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6373),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Name = "Rústico Borracha Peixe",
                            Price = 5.0582548073511532m,
                            Quantity = 44
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6389),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Impressionante Metal Camiseta",
                            Price = 45.9236989648018m,
                            Quantity = 37
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6431),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Name = "Licenciado Borracha Bacon",
                            Price = 96.172758145427644m,
                            Quantity = 33
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6450),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Fantástico Granito Frango",
                            Price = 14.302767065768092m,
                            Quantity = 55
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6467),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Lustroso Madeira Salsicha",
                            Price = 14.242806095055922m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6482),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Name = "Pequeno Concreto Peixe",
                            Price = 37.996726745447623m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 529, DateTimeKind.Local).AddTicks(6499),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Incrível Fresco Peixe",
                            Price = 60.29193128533939m,
                            Quantity = 40
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPriceAtMoment")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("SaleCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(565),
                            CustomerId = 12,
                            ProductId = 17,
                            ProductPriceAtMoment = 6.319214153827812m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 107.426640615072804m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(966),
                            CustomerId = 9,
                            ProductId = 11,
                            ProductPriceAtMoment = 6.524955823054124m,
                            ProductQuantity = 12,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 78.299469876649488m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(990),
                            CustomerId = 19,
                            ProductId = 18,
                            ProductPriceAtMoment = 2.0276981201142754m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 2.0276981201142754m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1008),
                            CustomerId = 3,
                            ProductId = 4,
                            ProductPriceAtMoment = 12.882626031228084m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 12.882626031228084m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1024),
                            CustomerId = 15,
                            ProductId = 13,
                            ProductPriceAtMoment = 12.779587653692554m,
                            ProductQuantity = 17,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 217.252990112773418m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1038),
                            CustomerId = 6,
                            ProductId = 8,
                            ProductPriceAtMoment = 11.06210690704253m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 154.86949669859542m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1080),
                            CustomerId = 1,
                            ProductId = 3,
                            ProductPriceAtMoment = 8.903861959995476m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 97.942481559950236m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1094),
                            CustomerId = 15,
                            ProductId = 7,
                            ProductPriceAtMoment = 11.668245089998831m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 163.355431259983634m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1109),
                            CustomerId = 16,
                            ProductId = 6,
                            ProductPriceAtMoment = 11.774414459876806m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 23.548828919753612m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1123),
                            CustomerId = 17,
                            ProductId = 20,
                            ProductPriceAtMoment = 19.993739926834544m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 199.937399268345440m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1137),
                            CustomerId = 11,
                            ProductId = 12,
                            ProductPriceAtMoment = 13.327332533056475m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 53.309330132225900m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1150),
                            CustomerId = 18,
                            ProductId = 9,
                            ProductPriceAtMoment = 1.246358770140798m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 4.985435080563192m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1165),
                            CustomerId = 19,
                            ProductId = 20,
                            ProductPriceAtMoment = 6.347453171791652m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 31.737265858958260m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1179),
                            CustomerId = 20,
                            ProductId = 19,
                            ProductPriceAtMoment = 15.844329574726525m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 316.886591494530500m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1192),
                            CustomerId = 4,
                            ProductId = 15,
                            ProductPriceAtMoment = 8.180982983798196m,
                            ProductQuantity = 15,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 122.714744756972940m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1205),
                            CustomerId = 3,
                            ProductId = 18,
                            ProductPriceAtMoment = 6.94714617513637m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 97.26004645190918m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1242),
                            CustomerId = 11,
                            ProductId = 2,
                            ProductPriceAtMoment = 13.702954135404289m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 123.326587218638601m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1256),
                            CustomerId = 7,
                            ProductId = 12,
                            ProductPriceAtMoment = 2.754736820309544m,
                            ProductQuantity = 4,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 11.018947281238176m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1269),
                            CustomerId = 4,
                            ProductId = 16,
                            ProductPriceAtMoment = 14.221855403058003m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 42.665566209174009m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1285),
                            CustomerId = 16,
                            ProductId = 14,
                            ProductPriceAtMoment = 5.64059496428849m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 5.64059496428849m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1300),
                            CustomerId = 8,
                            ProductId = 10,
                            ProductPriceAtMoment = 8.084138681488701m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 16.168277362977402m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1313),
                            CustomerId = 9,
                            ProductId = 10,
                            ProductPriceAtMoment = 15.335955977919283m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 168.695515757112113m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1327),
                            CustomerId = 10,
                            ProductId = 10,
                            ProductPriceAtMoment = 6.723023209412067m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 40.338139256472402m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1340),
                            CustomerId = 14,
                            ProductId = 4,
                            ProductPriceAtMoment = 12.965337386399724m,
                            ProductQuantity = 8,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 103.722699091197792m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1355),
                            CustomerId = 11,
                            ProductId = 10,
                            ProductPriceAtMoment = 4.623601145768681m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 41.612410311918129m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1369),
                            CustomerId = 5,
                            ProductId = 1,
                            ProductPriceAtMoment = 14.856928531926261m,
                            ProductQuantity = 18,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 267.424713574672698m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1404),
                            CustomerId = 13,
                            ProductId = 16,
                            ProductPriceAtMoment = 7.185153129750152m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 50.296071908251064m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1420),
                            CustomerId = 15,
                            ProductId = 4,
                            ProductPriceAtMoment = 10.539038182570423m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 63.234229095422538m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1433),
                            CustomerId = 8,
                            ProductId = 17,
                            ProductPriceAtMoment = 13.823760084964404m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 96.766320594750828m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1446),
                            CustomerId = 2,
                            ProductId = 11,
                            ProductPriceAtMoment = 3.591574529799584m,
                            ProductQuantity = 3,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 10.774723589398752m
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1459),
                            CustomerId = 7,
                            ProductId = 19,
                            ProductPriceAtMoment = 2.3680407977300652m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 14.2082447863803912m
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1472),
                            CustomerId = 13,
                            ProductId = 18,
                            ProductPriceAtMoment = 17.624991293475511m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 193.874904228230621m
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1485),
                            CustomerId = 7,
                            ProductId = 20,
                            ProductPriceAtMoment = 15.405372557657609m,
                            ProductQuantity = 5,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 77.026862788288045m
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1497),
                            CustomerId = 14,
                            ProductId = 19,
                            ProductPriceAtMoment = 16.44666311777464m,
                            ProductQuantity = 8,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 131.57330494219712m
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1509),
                            CustomerId = 19,
                            ProductId = 3,
                            ProductPriceAtMoment = 6.166115664426405m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 12.332231328852810m
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1522),
                            CustomerId = 15,
                            ProductId = 13,
                            ProductPriceAtMoment = 17.596785546625459m,
                            ProductQuantity = 2,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 35.193571093250918m
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1534),
                            CustomerId = 8,
                            ProductId = 16,
                            ProductPriceAtMoment = 11.885759803764651m,
                            ProductQuantity = 1,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 11.885759803764651m
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1570),
                            CustomerId = 12,
                            ProductId = 18,
                            ProductPriceAtMoment = 4.295114453816597m,
                            ProductQuantity = 20,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 85.902289076331940m
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1583),
                            CustomerId = 17,
                            ProductId = 20,
                            ProductPriceAtMoment = 11.80308084645329m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 188.84929354325264m
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1596),
                            CustomerId = 12,
                            ProductId = 14,
                            ProductPriceAtMoment = 2.3196042790693959m,
                            ProductQuantity = 10,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 23.1960427906939590m
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1608),
                            CustomerId = 7,
                            ProductId = 11,
                            ProductPriceAtMoment = 12.159183331515941m,
                            ProductQuantity = 9,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 109.432649983643469m
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1620),
                            CustomerId = 17,
                            ProductId = 4,
                            ProductPriceAtMoment = 7.166430621313869m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 114.662889941021904m
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1632),
                            CustomerId = 6,
                            ProductId = 10,
                            ProductPriceAtMoment = 11.931447153874432m,
                            ProductQuantity = 7,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 83.520130077121024m
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1645),
                            CustomerId = 10,
                            ProductId = 19,
                            ProductPriceAtMoment = 6.162229219187121m,
                            ProductQuantity = 11,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 67.784521411058331m
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1657),
                            CustomerId = 13,
                            ProductId = 5,
                            ProductPriceAtMoment = 2.7072312922746927m,
                            ProductQuantity = 19,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 51.4373945532191613m
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1670),
                            CustomerId = 12,
                            ProductId = 16,
                            ProductPriceAtMoment = 12.023828367263264m,
                            ProductQuantity = 6,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 72.142970203579584m
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1683),
                            CustomerId = 16,
                            ProductId = 3,
                            ProductPriceAtMoment = 15.249849954103564m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 213.497899357449896m
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1719),
                            CustomerId = 11,
                            ProductId = 10,
                            ProductPriceAtMoment = 10.300325672378646m,
                            ProductQuantity = 16,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 164.805210758058336m
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1733),
                            CustomerId = 7,
                            ProductId = 17,
                            ProductPriceAtMoment = 5.460148371093667m,
                            ProductQuantity = 13,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 70.981928824217671m
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2023, 6, 28, 8, 26, 32, 531, DateTimeKind.Local).AddTicks(1746),
                            CustomerId = 4,
                            ProductId = 4,
                            ProductPriceAtMoment = 10.223994438536119m,
                            ProductQuantity = 14,
                            SaleCancelled = false,
                            SaleNumber = "20230628082632",
                            Total = 143.135922139505666m
                        });
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", null)
                        .WithMany("ProductsPurchased")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Sale", b =>
                {
                    b.HasOne("WebSales.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebSales.Domain.Entities.Product", "Product")
                        .WithMany("ProductsSold")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSales");

                    b.Navigation("ProductsPurchased");
                });

            modelBuilder.Entity("WebSales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductsSold");
                });
#pragma warning restore 612, 618
        }
    }
}
